# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-ast
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 7638d0035a770dd67283b7d464e4db3c0043f609
    hooks:
    -   id: python-no-eval
-   repo: https://github.com/asottile/reorder_python_imports
    rev: d5ccddd9900fe44838800815c7d1dba2b8837490
    hooks:
    -   id: reorder-python-imports
