colors:
  - indianred
  - seagreen
  - mediumblue
  - goldenrod
  - indigo
  
graph_config:
  modeBarButtonsToAdd:
    - drawclosedpath
    # - drawcircle
    - drawrect
    # - eraseshape

xtype_to_mode:
  numeric: markers
  datetime: lines