colors:
  - indianred
  - seagreen
  - mediumblue
  - goldenrod
  - indigo

graph_config:
  modeBarButtonsToAdd:
    - drawclosedpath
    - drawrect
    # - drawcircle
    # - eraseshape

graph_layout:
  height: 655
  dragmode: drawclosedpath
  template: seaborn
  margin:
    l: 80
    r: 30
    t: 60
    b: 80

xtype_to_mode:
  numeric: markers
  datetime: lines

table_style:
  cell_width: 400
  table_height: 660
  header:
    backgroundColor: rgb(210, 210, 210)
    color: black
    fontWeight: bold
    textAlign: center
  data:
    backgroundColor: white
    color: black
